name: Unit Tests
on: [push, pull_request]
permissions: read-all
jobs:
  vitest:
    name: Vitest on ${{ matrix.os }} (Node.js v${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        node: ["20", "22", "24"]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
      - name: Setup node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # 4.0.3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
env:
  YARN_GPG: no
